version: '2'

services:
  web:
    image: eu.gcr.io/rdx-net-public-registry/phpmyadmin:${IMAGE_TAG:-latest}
    build:
      context: .
    ports:
      - '81:80'
    environment:
      SECRET_COOKIE_BASE: sekrit-cookie-base-is-injected-by-the-platform
      PMA_ARBITRARY: 0
      PMA_HOSTS: "mysql,another-database"
      # PMA_VERBOSES: local,remote
      # PMA_USER: root
      # PMA_PASSWORD: root-password
networks:
  default:
    external:
      name: purasu-local
